Sector-Crescent/Hullrot

Resources/Prototypes/Entities/Objects/Devices/pda.yml
Resources/Prototypes/_Crescent/Parallaxes/fastspace.yml

Description.
---
---
<p>
</p>
</details>
---
:cl:

Textureshit

---

Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
Content.Server/Cargo/Systems/CargoSystem.Orders.cs
Content.Server/Cargo/Systems/CargoSystem.cs
Content.Server/Cargo/Systems/StockMarketSystem.cs
Content.Server/VendingMachines/VendingMachineSystem.cs
Content.Shared/VendingMachines/VendingMachineComponent.cs

Description.
---
---
<p>
</p>
</details>
---
:cl:

Fix Cargo + Vendors

---

Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
Content.Server/Shuttles/Systems/ShuttleConsoleSystem.cs
Content.Shared/Shuttles/BUIStates/ShuttleBoundUserInterfaceState.cs

Description.
---
---
<p>
</p>
</details>
---
:cl:

Poorly fix shuttle docking

---

Content.Client/Holopad/HolopadWindow.xaml.cs
Content.Server/Holopad/HolopadSystem.cs
Content.Server/_NF/Station/Components/StationRenameHolopadsComponent.cs
Content.Server/_NF/Station/Systems/StationRenameHolopadsSystem.cs
Content.Shared/Holopad/HolopadComponent.cs
Resources/Prototypes/_NF/Entities/Structures/Machines/holopad.yml

ports the ship holopad stuff from frontier

ship holopads

---

Content.Server/Shuttles/Systems/ShuttleConsoleSystem.cs
Content.Shared/Shuttles/BUIStates/ShuttleBoundUserInterfaceState.cs

Description.
---
---
<p>
</p>
</details>
---
:cl:

Fix shuttle consoles

---

Resources/Prototypes/_Crescent/Maps/Ships/NCWL/kavkaz.yml

kavkaz fix

---

Resources/Prototypes/_Crescent/Entities/Recipes/Lathes/imperialcrafts.yml

fixes 2 imperial research errors in the console

fix 2 imperial research errors

---

Resources/Maps/_Crescent/Stations/kalsuzerai.yml

aisha removed some prototypes and this makes kal suzerai not spawn 
i removed those prototypes, loaded ingame and it worked
gitban me if this doesn't work, i tested it

fixes kal suzerai having broken protos and not spawning

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Recipes/Lathes/security.yml
Resources/Prototypes/_Crescent/Entities/Objects/Ammunition/cannonammo.yml
Resources/Prototypes/_Crescent/Entities/Recipes/Lathes/ammo.yml

Description.
---
---
<p>
</p>
</details>
---
:cl:

Ammo Fab lathe fixes ,Idna buffs.

---

Content.Client/Shuttles/UI/ShuttleNavControl.xaml.cs

Fixes https://github.com/Sector-Crescent/Hullrot/issues/164

Fixes ship dots PROPERLY  this TIME.

---

Resources/Prototypes/_Crescent/ambient_music.yml

hopefully fixes all the yaml linter errors related to ambient music

ambient music yaml linter errors

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/wallmed.yml
Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml

-adds gauze to medical vends 
-removes random inventory from sustance-vendor making it full on spawn 
lol

vends-changes

---

Resources/Prototypes/Entities/Structures/Walls/girders.yml
Resources/Prototypes/_Crescent/Entities/Shipguns/Bullets/projectiles.yml

Description.
---
---
<p>
</p>
</details>
---
:cl:

Ship Weapon Balance Changes

---

Content.Shared/CCVar/CCVars.Interactions.cs
Content.Shared/Movement/Systems/SharedMoverController.Input.cs
Content.Shared/Movement/Systems/SharedMoverController.Relay.cs

makes the "walk by default" setting also apply to jetpacks and mechs

[WWDP port] makes the movement settings consistent between mech/jetpacks and normal movement

---

Resources/Prototypes/_Crescent/Entities/Structures/lathe.yml

add ingots insertion to IPM fablathe

---

Resources/Prototypes/Entities/Markers/Spawners/Random/salvage.yml
Resources/Prototypes/Entities/Structures/Walls/asteroid.yml
Resources/Prototypes/Entities/World/Debris/asteroids.yml
Resources/Prototypes/Entities/World/Debris/wrecks.yml
Resources/Prototypes/_NF/Entities/World/Debris/asteroids.yml

adds tungsten and copper to all asteroids. **values and which asteroids deserve these materials need a look**
adds 3 new spawners for scrap. **what materials they spawn need a look**
adds said new spawners to wrecks. **exact spawn chances need a look**

adds tungsten and copper to asteroids. adds new spawners to wrecks.

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
Resources/Prototypes/_Crescent/Entities/Objects/Weapons/shotguns.yml

Changed the AMRs to instantly kill targets.
Partisan SMG now has a 8 round burst with 0.8 burst fire delay
Pioneer shotgun damage multiplier increased from 1 to 2.5

Weapon balance changes for unionfall (requested by .2)

---

Resources/Prototypes/_Crescent/Catalog/Jukebox/Standard.yml

davai misattributed, I forgot to push this fix yesterday.

Fix Davai attribute

---

Resources/Maps/_Crescent/Explorables/psionicHealWreck.yml

Description.
---
---
<p>
</p>
</details>
---
:cl:

Deep Lore Wreck

---

Resources/Prototypes/_Crescent/DogtagStore/currency.yml
Resources/Prototypes/_Crescent/Entities/Materials/scrap.yml
Resources/Prototypes/_Crescent/Entities/Objects/Misc/identification_cards.yml
Resources/Prototypes/_Crescent/Entities/Objects/Misc/trade.yml
Resources/Prototypes/_Crescent/PortedShit.yml

Description.
---
---
<p>
</p>
</details>
---
:cl:

SAW + GSC Store

---

Content.Client/Shuttles/UI/ShuttleNavControl.xaml.cs

Description.
---
---
<p>
</p>
</details>
---
:cl:

Multi-threaded Shuttle Console + Hardcore Grid Culling

---

Resources/Prototypes/_Crescent/Entities/Objects/Specific/fighters.yml
Resources/Prototypes/_Crescent/Maps/Ships/NCSP/harpy.yml
Resources/Prototypes/_Crescent/Maps/Ships/NCSP/hornetsnest.yml
Resources/Prototypes/_Crescent/Maps/Ships/NCSP/hulk.yml
Resources/Prototypes/_Crescent/Maps/Ships/NCSP/meatwagon.yml
Resources/Prototypes/_Crescent/Maps/Ships/NCSP/taipan.yml

Description.
---
---
<p>
</p>
</details>
---
:cl:

Quick fixes

---

Content.Server/Preferences/Managers/IServerPreferencesManager.cs
Content.Server/Preferences/Managers/ServerPreferencesManager.cs
Content.Server/_NF/Shuttles/Bank/BankSystem.cs
Resources/Prototypes/_Crescent/Markers/jobspawners.yml
Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_claw.yml

Description.
---
---
<p>
</p>
</details>
---
:cl:

Remove Tax Fraud

---

Content.Server/Xenoarchaeology/Equipment/Components/ArtifactAnalyzerComponent.cs

from 40 to 5 seconds on analysis console
pearcat blooms.

Fix everything wrong with R&D ever

---

Resources/Prototypes/_Crescent/Entities/Recipes/Lathes/shinohara.yml

Changed fighter cannons to use similar recipes as the mechs, increased cost on fighter weapons.

Fighter / Mech cost Parity

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
Resources/Prototypes/_Crescent/Entities/Objects/Tools/weapon_cases.yml

added EmpOnTrigger to grenade case whitelist so EMP nades come in it

emp nade fix

---

Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_doctor.yml
Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_fleetkapitan.yml
Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_industry_taskmaster.yml
Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_partisan.yml
Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_worker_overboss.yml

doctor gets ncwl jail for morgue
partisan gets armory
fleetkapitan/overseer/coordinator doesn't get kommissar access

ncwl access fix again. how did this get undone .wtf

---

Resources/Prototypes/_Crescent/Entities/Objects/Weapons/rifles.yml

Removes SVD burst

---

Resources/Prototypes/_Crescent/Entities/Clothing/NCWL/OuterClothing/armor.yml

NCWL hardsuit had .85 walkspeed/sprint
DSM hardsuit had .9 walkspeed/sprint
I made them the same at .9
im evergreenblooming it

Equalize NCWL DSM hardsuit walk speeds

---

Resources/Prototypes/_Crescent/Entities/Structures/mothership_consoles.yml
Resources/Prototypes/_Crescent/Maps/Ships/NCSP/cleaver.yml
Resources/Prototypes/_Crescent/Maps/Ships/NCSP/eradicator.yml

changelog:
- gsc mothership console added cleaver and eradicator
- prices for both ships increased so if you sell them you are in minus profit
DAS IT

gorlex-mothership-console

---

Resources/Prototypes/Entities/Mobs/Player/ipc.yml

Title
:cl:
- tweak: Morbed Atyrian for IPC and brung back binary

[SALT PR, electrical boogaloo] morb atyrian to IPC, add back binary

---

Resources/Prototypes/_Crescent/Entities/Structures/dispensers.yml

Description.
---
---
<p>
</p>
</details>
---
:cl:

DSM Trade Goods

---

Resources/Maps/_Crescent/Shuttles/Civilian/comet.yml
Resources/Prototypes/_Crescent/Entities/Structures/computers.yml
Resources/Prototypes/_Crescent/Maps/Ships/Civilian/comet.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_shipyard.yml

adds 2 ships dotto mapped 
icm comet 
pta hammerhead 
creates prototype for comet
adds them into civilian shipyard console 
https://github.com/user-attachments/assets/6013ce13-5f9d-490f-911b-af6c15f7130b

indie-content

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml

make tasers 3 shot stuns instead of 1

---

Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml

tourniquets only deal asphyx damage now
legacy port
bloodpacks heal 5 instead of 2.5 bloodloss

tourniquet no longer deal 10 damage and more bloodloss is healed per bloodpacks

---

Content.Server/Abilities/Psionics/PsionicFamiliarSystem.cs
Content.Shared/Actions/Events/SummonPsionicFamiliarActionEvent.cs
Resources/Locale/en-US/_Crescent/psionics/psionic-powers.ftl
Resources/Prototypes/_Crescent/Actions/psionics.yml
Resources/Prototypes/_Crescent/Entities/Mobs/NPCs/animals.yml
Resources/Prototypes/_Crescent/Psionics/psionics.yml

Literally just a psionic power that summons a mothroach. Ignore my earlier failure to PR this (it's 3 AM, cut me some slack).
no

Summon Mothroach

---

Resources/Prototypes/_Crescent/Roles/Jobs/Shared/gliessiandeputy.yml
Resources/Prototypes/_Crescent/Roles/Jobs/Shared/gliessiandockmaster.yml
Resources/Prototypes/_Crescent/Roles/Jobs/Shared/gliessiansheriff.yml

no more newfriends getting on the roles and cluelessly wandering about

whitelist and timelock Gliess minutemen roles and dockmaster

---

Content.Client/Shuttles/UI/MapScreen.xaml.cs
Content.Server/Atmos/EntitySystems/AtmosphereSystem.Monstermos.cs
Content.Server/Shuttles/Components/IFFConsoleComponent.cs
Content.Server/Shuttles/Systems/ShuttleConsoleSystem.cs
Content.Server/Shuttles/Systems/ShuttleSystem.IFF.cs
Content.Server/_Crescent/ProjectilePhasePreventSystem.cs
Resources/Prototypes/_Crescent/Entities/Shipguns/Bullets/projectiles.yml
Resources/Prototypes/_Crescent/Maps/Stations/gliess.yml

Description.
---
---
<p>
</p>
</details>
---
:cl:

The one big fix

---

Resources/Prototypes/_Crescent/Entities/Objects/Weapons/donator.yml

Fixes the inhand for the couroux whoopsies

Donor weapon inhand fix

---

Resources/Prototypes/_Crescent/Entities/Objects/Weapons/flamethrowers.yml

last second fix lol

---

Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml

re-adds shortband to all headsets after it was removed
---
:cl:
- add: Adds shortband to all headsets

Adds shortband to all headsets(again)

---

Resources/Prototypes/Entities/Structures/Walls/girders.yml

legacy port
makes girders vaultable

vaultable girders

---

Resources/Prototypes/_Crescent/Entities/Objects/Weapons/donator.yml

fix plasmacutter size

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
Resources/Prototypes/_Crescent/Entities/Objects/Weapons/rifles.yml
Resources/Prototypes/_Crescent/Entities/Objects/Weapons/shotguns.yml

adjusts the descriptions for all conscript weapons
Changed all conscript weapon deceptions to be less wall of Text's
Description.
This Changes every conscript weapon to a lower Word count
---
---
<p>
</p>
</details>
---
:cl:

Adjusts descptions for alll conscript weapons

---

Resources/Prototypes/_Crescent/Entities/Objects/Weapons/donator.yml

original harassed me to lower the recoil or some shit on his shitty broken gun and i couldn't be bothered to argue

1 letter yaml change

---

Resources/Maps/_Crescent/Stations/hayes.yml

add IPM's autopeddler to Hayes

---

Resources/Maps/_Crescent/Stations/countsman.yml

countsman speed buff, from 7.5 to 10knt

---

Content.Server/_Crescent/ProximityFuse/ProximityFuseSystem.cs
Resources/Prototypes/_Crescent/Entities/Shipguns/Bullets/projectiles.yml
Resources/Prototypes/_Crescent/Traits/traits.yml

dumb language menu bloat + emergency prince nerf

---

Resources/Maps/_Crescent/Stations/hayes.yml

makes it so the station doesn't get spaced as easily from the bridge and on the southeast side
also makes the windows on the docking prong tough aswell

reinforces hayes' windows and exterior walls on the southeast

---

Resources/Prototypes/_Crescent/DogtagStore/catalog_IPM.yml

the values were overtuned, now they should be more reasonable to acquire and actually sell without underselling the value of the cybernetic part

lower IPM autopeddler costs

---

Content.Shared/Weapons/Ranged/Components/GunComponent.cs

makes all firearms 50% faster
bullet speed change in action:
https://github.com/user-attachments/assets/314e98b1-66e5-4a66-bb7f-f6cf420800d8

make gun bullets 50% faster

---

Resources/Maps/_Crescent/Shuttles/NCSP/spriggan.yml

What it says on the title, i removed the Spriggan's IFF capabilities, replaced it with a comms console instead.
:cl:
- remove: Removed Spriggan IFF cloaking capabilities

Spriggan IFF cloaking removal

---

Resources/Maps/_Crescent/Shuttles/Civilian/roachling.yml

Fixed the nav module label for the Roachling's guns, since i apparently forgot to label them. Oopsies!
:cl:
- fix: added labels to the Roachling's nav console modules for better user experience.

fixed the module labels on the Roachling

---

Content.Shared/_Crescent/Hardpoints/SharedHardpointSystem.cs

i didnt account for shipguns being removed from hardpoints by anything other than wrenching so this solves hardpoints from becoming perma-fucked
simply makes shipguns send a message to the hardpoint when they're destroyed (same code as being deanchored)

fixes hardpoint issues with removal and breaking

---

Resources/Prototypes/_Crescent/Roles/Jobs/DSM/levyman.yml
Resources/Prototypes/_Crescent/Roles/Jobs/DSM/scribe.yml

Hullrotfaction component FIX

---

Resources/Prototypes/Catalog/ReagentDispensers/chemical.yml

Adds welding fuel and silver to the chemdispenser

Adds welding fuel and silver to the chemdispenser

---

Resources/Maps/_Crescent/Stations/jackal.yml

What it says on the title. Edited the Shuttlecomponent MaxLinearVelocity to 15 knts. 
:cl:
- tweak: Nerfs the Jackal's speed to 15 knts

Nerfed Jackal speed to 15 Knts
