Sector-Crescent/Hullrot

Content.Server/Holopad/HolopadSystem.cs, Content.Server/_Crescent/Holopad/ShipRenameHolopadComponent.cs, Content.Server/_NF/Station/Systems/StationRenameHolopadsSystem.cs, Content.Shared/Holopad/HolopadComponent.cs, Resources/Prototypes/_Crescent/Maps/Ships/Civilian/termite.yml, Resources/Prototypes/_Crescent/Maps/base.yml
reuses the same functionality the UseStationName does to rename a grid's holopad.
but this works from the other end by simply adding a component to the grid instead of having to use a special holopad 
(and consequently remapping all the ships instead of adding a little line to each .yaml prototype)
still needs to test but it appears that the commands are not working very intuitively, though I've added the change to the Termite, if anyone can pull this on their end and check it out it would be quite Cool.
What it should do is cause the holopad of a termite to be named NZT-69 or w/e when called, this name change is initialized on the holopad object initializing itself (if the ship grid has the ShipRenameHolopadComponent)
---
- [x ] add logic
- [] test
- [] add the component to every ship's …
=> fixes holopad renaming issues

Resources/Prototypes/Entities/Clothing/Belt/belts.yml, Resources/Prototypes/_EE/Entities/Clothing/BieselRepublic/Modsuits/legionnaire.yml, Resources/Prototypes/_EE/Entities/Clothing/BieselRepublic/belts.yml, Resources/Prototypes/_EE/Entities/Clothing/SolAlliance/SAN/Modsuits/CSA-85x.yml, Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/apocryphal.yml, Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/corporate.yml, Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/engineering-responsory.yml, Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/inquisitory.yml, Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/janitorial-responsory.yml, Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/leader-responsory.yml, Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/medical-responsory.yml, Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/praetorian.yml, Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/security-responsory.yml, Resources/Prototypes/_TG/Entities/Clothing/Modsuits/SyndicateModsuits.yml
in a previous pr i made it so that hardsuits dont use this component anymore and use FootstepModifier to replace foosteps instead of **adding two additional sounds on top of the regular footstep**. this currently affects webbings the worst in rebase because they make this godawful loud sound which plays every damn footstep. equipment alternatives such as regular belts and drop pouches have almost identical functionality but without demolishing your ears
on BELTS: removed the component
on MODSUITS/OTHERS: replaced with FootstepModifier
on JESTER BELLS/WEIRD CYBERSUN STEALTH SUIT: left alone
https://github.com/user-attachments/assets/19fabe7a-c43a-47d0-b041-8fbc7e54d600
=> nukes almost every instance of EmitsSoundOnMove (modsuits replaced with FootstepModifier)

Resources/Prototypes/CharacterItemGroups/Generic/backpackGroups.yml, Resources/Prototypes/CharacterItemGroups/Generic/beltGroup.yml, Resources/Prototypes/_Crescent/CharacterItemGroups/Jobs/Empire/noble.yml, Resources/Prototypes/_Crescent/Loadouts/Back/backpacks.yml, Resources/Prototypes/_Crescent/Loadouts/Empire/belt.yml, Resources/Prototypes/_Crescent/Loadouts/Empire/items.yml, Resources/Prototypes/_Crescent/Roles/Jobs/DSM/adjutant.yml, Resources/Prototypes/_Crescent/Roles/Jobs/DSM/governor.yml
Adds all of hullrot's backpacks and the DSM noble weapons and their sheathes to the loadout system for the higher ranking roles of the Mandate.
also moves or removes some roles' items that occupy the belt to allow the weapon sheath to spawn on the player equipped 
<h1>Media</h1>
https://github.com/user-attachments/assets/2c1c03c5-69d6-4bc6-a894-96471e00c723
=> Adds the DSM ornamental noble melees and all hullrot backpacks to their respective factions available in the loadout system

Resources/Prototypes/_Crescent/Entities/SpaceArtillery/shells.yml
when we removed ProjectilePhasePrevent from stuff we removed it from vulcans and pdt guns
we added it back to vulcans but forgot about PDT guns which made them phase thru stuff entirely
this fixes that by adding it back
=> fixes pdt gun projectiles phasing thru ships and being useless

Resources/Prototypes/Entities/Objects/Tools/jetpacks.yml
Fixes one letter error causing jetpacks to not be able to go into suit storage slot
=> jetpack-fix

Content.Shared/Mech/EntitySystems/SharedMechSystem.cs, Content.Shared/Mech/Equipment/Components/MechEquipmentComponent.cs
Description.
Just the beginning of getting a few simple systems in for manned fighters using mech code, including the ability to apply the radar component for navigation, as with the ability to prevent guns from firing on grids/gravity.
---
---
:cl:
-add: Added PreventFireOnGrid component, preventing guns from well, firing on grids/gravity
-add: Added mech radar action, so you they can use a component to have variable radars (giving some craft more radar than some, etc etc)
=> Mech Components to not fire on gravity + Radar

Resources/Prototypes/_Crescent/Maps/Stations/kal.yml
on request of DSMcord
also to make them be able to fly in a V wedge or something for larp
larp
makes ritter pop 3 instead of just 1
=> 3 ritters instead of 1

Resources/ServerInfo/_Crescent/ServerRules/HullrotRuleset.xml
Old: `https://wreakhavoconthemiddleclass.github.io/ncwl-docs/guides/introduction/`
New: `https://ncwldocs.github.io/guides/introduction/`
Updating a URL in the server rules.
N/A
N/A
:cl:
- tweak: updated NCWL Docs URL in server rules
=> Update NCWL Docs URL in HullrotRuleset.xml

Resources/Prototypes/_Crescent/Entities/Objects/Misc/idchips.yml
Gave the NTID chips a static sell price. Below are the prices for the chips ordered from lowest to highest. You can sell these NTID chips for money at any sell pad. Temporary addition until Aisha adds in a proper bounty post, mostly meant for NCWL so they can get on their feet.
Low-Tier Criminal: 5,000 Taypani Yen
Regular Criminal: 8,500 Taypani Yen
Abyssal Creature: 10,000 Taypani Yen
---
---
:cl: ShirouAjisai
- add: Gave NTID chips a static sell price.
=> NTID Chips Worth Money

Resources/Prototypes/Loadouts/Generic/head.yml, Resources/Prototypes/Loadouts/Generic/items.yml, Resources/Prototypes/Loadouts/Generic/mask.yml
---
Fixed up the item loadouts a bit
Fixed bountyhunterhat to be colorable like description says. 
Dropped cost of many ITEMS
Added back the handheld crewmonitor as it was lost during la rebazo...
Removed single cig
Removed blue tank (useless) and extended emergency (nonexistent) 
Removed random book (go to library)
Removed single water bottle
Removed MRE flask as there's many alternatives that you can color.
Moved breathmask to masks section.
=> Cheaper loadouts AND MORE

Resources/Prototypes/_Crescent/Entities/Shipguns/Guns/turrets.yml
swarmers are the lightest missile peashoters, lancers are the medium versions according to some nerds that noticed this discrepancy
=> lancer MRM is called a medium instead of light missile system now

Resources/Locale/en-US/_Crescent/research/researchNEW.ftl, Resources/Prototypes/_Crescent/Entities/Objects/Ammunition/Projectiles/mech.yml, Resources/Prototypes/_Crescent/Entities/Objects/Specific/mech_weapons.yml, Resources/Prototypes/_Crescent/Entities/Recipes/Lathes/imperialcrafts.yml, Resources/Prototypes/_Crescent/Entities/Structures/lathe.yml, Resources/Prototypes/_Crescent/Research/imperial.yml
Uses the existing plasma rifle and plasma cannon mech sprites as the following weapons for the DSM to research:
IRM 'Verdict' 250c exosuit plasma repeater: Basically a mech portable plasma caster with a lightly changed damage values, less deadly explosion, and higher than average energy usage.
IRM 'Judgement' 600c exosuit plasma cannon: A far superior upgrade that has the worst power consumption to only have 30 shots before depowering the mech, BUT is able to kill most mechs in two to three shots and heavily damage ships.
=> Adds in the DSM plasma mech weapons + tech

Resources/Maps/_Crescent/Stations/novabalreska.yml, Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_commandant.yml, Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_doctor.yml, Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_fleetkapitan.yml, Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_industry_taskmaster.yml, Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_partisan.yml, Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_worker.yml, Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_worker_overboss.yml
- fixes ncwl access on balreska
- - doctors get jail access (for morgue)
- - kommissar gets no administrator/kommandante access
- - partisans get armory access
- - civ leads get no kommissar access
- union workers get tradeband. fixed yaml formatting on partisan languages
- parade gear taken off of kommandante, since balreska spawns it in a locker
=> NCWL ACCESS + SMALL TWEAKS

Resources/Maps/_Crescent/Shuttles/NCSP/scabrak.yml, Resources/Prototypes/_Crescent/Maps/Ships/NCSP/scabrak.yml
This pr aims to lower the price of the scabrak mining ship due to the price of 100k is not fit for a mining barge. It was made by:
fixing the cost of scabrak ((mining ship)) being 100k by lowering it to 72k. The grid itself now costs 59~k. It was achieved by mainly gutting majority of stuff from it. The list of changes:
- scabrak gained pipework, waste and distro both are coloured
- lost gyroscope 2 -> 1, additionally replaced it with the worse one 
- armory guns are replaced with singular ncsp pistol and a box of 9x19 ammo
- lost wall-mounted nanomed 
- lost its ripley and 2 claws for it
- lost box of 20mm ammo 
Other notes : after running appraisegrid on the grid realised that majority of stuff such as and gyroscopes had an odd price of 2000 for all kinds of gyroscopes, NFSD, Security …
=> Scabrak cost fix

Resources/Prototypes/_Crescent/Entities/Objects/Weapons/pistols.yml
SHI has improved cost efficiency and profits by removing some parts at the expense  of the gun being semi auto, it's not even full auto, it's pull the trigger and the magazine is fired until it runs out. Expect your local vagrant to actually have a couple of these, throwing em away after each use as god intended. Added .6 chance on being thrown against a wall to fire.
Also cleans up the YML for blastpop.
=> Shi Burstpop

Resources/Maps/_Crescent/Event/meteor.yml, Resources/Maps/_Crescent/Shuttles/CMM/adjudicator.yml, Resources/Maps/_Crescent/Shuttles/Civilian/kite.yml, Resources/Maps/_Crescent/Shuttles/DSM/royal.yml, Resources/Maps/_Crescent/Shuttles/Fog/autoscout.yml, Resources/Maps/_Crescent/Shuttles/Fog/pounder.yml, Resources/Maps/_Crescent/Shuttles/NCSP/harpy.yml, Resources/Maps/_Crescent/Shuttles/NCWL/bogatyr.yml, Resources/Maps/_Crescent/Shuttles/NCWL/ivarod.yml, Resources/Prototypes/_Crescent/Catalog/Fills/Crates/shuttleammo.yml, Resources/Prototypes/_Crescent/Entities/Shipguns/Bullets/ammo.yml, Resources/Prototypes/_Crescent/Entities/Shipguns/Bullets/cartridges.yml, Resources/Prototypes/_Crescent/Entities/Shipguns/Bullets/projectiles.yml, Resources/Prototypes/_Crescent/Entities/Shipguns/Guns/fixedpoints.yml, Resources/Prototypes/_Crescent/Entities/Shipguns/Guns/turrets.yml, Resources/Prototypes/_Crescent/_Hyperwar/Wardrobes.yml, Resources/Prototypes/_Crescent/tags.yml
sumitomo missles are 40mm blast/baton/emp grenades in code
this PR gives them entirely separated yaml that should not interact with grenades anymore
also, kite had a missing MV wire under the substation. this has been fixed
ivarod had improper linking for its frontal 120mms. this fixes that, along with putting proper hardpoints. this is a bandaid fix until aisha/ninrub finishes the remap.
=> separates sumitomo missles from 40mm missles. kite fix. ivarod fix

Resources/Prototypes/Entities/Mobs/base.yml
EscalRot14. Our Certainly Furious Escalation.
enables freelook for players. that's it. peakium.
https://github.com/user-attachments/assets/85ebf615-68db-41a7-81cf-6267cd9d9988
:cl: Ghost581
- add: You can now free look by pressing spacebar. The key is rebindable.
=> enable freelook on player characters, you can now press spacebar to toggle it

Resources/Prototypes/_Crescent/Roles/Jobs/SHI/board.yml, Resources/Prototypes/_Crescent/Roles/Jobs/SHI/employee.yml, Resources/Prototypes/_Crescent/Roles/Jobs/SHI/executive.yml, Resources/Prototypes/_Crescent/Roles/Jobs/SHI/highsec.yml, Resources/Prototypes/_Crescent/Roles/Jobs/SHI/medtech.yml, Resources/Prototypes/_Crescent/Roles/Jobs/SHI/security.yml
Updates the Shinohara roles' default loadouts, and changed playtime requirements for specific roles.
- Added Shinohara courier bags as a default option for all SHI roles.
- Gave Board Executive their suit jacket back.
- Removed HighSec's armor.
- Removed HighSec's and CorpSec's laser pistol.
- Gave Salaryman their high-vis vest and fingerless gloves back.
- Gave MedSpec Researchers latex gloves and a labcoat.
- Reduced playtime requirement for CorpSec from 5 hours to 2.
- Added playtime requirement for Board Executive: 4 hours.
=> SHI Gear & Playtime Fixes

Content.Server/StationEvents/BasicStationEventSchedulerSystem.cs, Content.Server/StationEvents/Components/BasicStationEventSchedulerComponent.cs, Content.Server/StationEvents/Components/RampingStationEventSchedulerComponent.cs, Content.Server/StationEvents/EventManagerSystem.cs, Content.Server/StationEvents/RampingStationEventSchedulerSystem.cs, Content.Shared/CCVar/CCVars.Events.cs, Resources/Locale/en-US/_Crescent/events/events.ftl, Resources/Prototypes/GameRules/events.yml, Resources/Prototypes/GameRules/roundstart.yml, Resources/Prototypes/_Crescent/Events/ship_gamerules.yml, Resources/Prototypes/_Crescent/GameRules/hullrotGamemodes.yml, Resources/Prototypes/_Crescent/GameRules/roundstart.yml, Resources/Prototypes/game_presets.yml
fixes #402, fixes #403 
This PR could use some scrutiny since it's relatively complex, but it's been tested and is mostly a port of upstream code.
Fix for random events not firing.
- Fixed a prototype error on the SHI and PTA trade ship events
- Manually ported minimal required portions of space-wizards/space-station-14#29320
- Added HullrotEventScheduler to the Freeplay game mode
- Fixed broken event descriptions
- Assorted tweaks for compatibility
https://github.com/user-attachments/assets/308b7a11-d439-44f8-8ac0-761bda23ee0d
Video uses minimal "time before event" and "time between events" values for testing only.
- fix: Random events work again
=> Random events fix

Content.Server/Abilities/Psionics/PsionicAbilitiesSystem.cs, Content.Server/Nutrition/Components/FoodComponent.cs, Content.Server/_Crescent/Magic/PsionicBrainEatingSystem.cs, Content.Shared/Psionics/PsionicComponent.cs, Content.Shared/_Crescent/Magic/PsionicBrainComponent.cs
Whenever you eat a former Psion's brain, you will get whatever powers they had. This can be extended by defining a new brain in .YML that has a set of powers already.
This PR was a commision by `bomk.` on Discord.
=> Psionic Braineating

Resources/Maps/_Crescent/Shuttles/NCSP/Shanty.yml, Resources/Maps/_Crescent/Shuttles/NCSP/caracal.yml, Resources/Maps/_Crescent/Shuttles/NCSP/rattler.yml, Resources/Maps/_Crescent/Shuttles/NCSP/rockchipper.yml, Resources/Prototypes/_Crescent/DogtagStore/catalog_SAW.yml, Resources/Prototypes/_Crescent/DogtagStore/presets.yml, Resources/Prototypes/_Crescent/Entities/Materials/scrap.yml, Resources/Prototypes/_Crescent/Entities/Objects/Misc/shiplpcs.yml, Resources/Prototypes/_Crescent/Entities/Structures/mothership_consoles.yml, Resources/Prototypes/_Crescent/Maps/Ships/NCSP/caracal.yml, Resources/Prototypes/_Crescent/Maps/Ships/NCSP/hyena.yml, Resources/Prototypes/_Crescent/Maps/Ships/NCSP/rokh.yml, Resources/Prototypes/_Crescent/Maps/Ships/NCSP/shanty.yml
This pr aims to fix all the leftovers in SAW shipyard from the rebase, while also re-enabling some of the things that were already mapped but not implemented. 
Changelog: 
- Reworks SAW mothership console for saws, removing ships like Amadeus from round start
- Fixes prices in the same console by checking their price through appraise-grid and increasing the price by 10k/20k~ depending on the grid. Examples: Hyena and Shanty, where Shanty can now be bought from fresh character for 24k while Hyena now costing 82k instead of 100k while grid costed only 70k~ 
- Overhauls Shanty, now having a universal hardpoint for its plasma caster 
- Fixes Rock-chipper, now it also received its hardpoints for exhumers
- Fixes Caracal not having hardpoints 
- Nerfs Rattler, removing the GSC suit and …
=> SAW-mapping-fixes

Resources/Prototypes/_Crescent/Entities/Recipes/Lathes/imperialcrafts.yml
Parity with NCWL's light mech cost. I had used the paladin's recipe as a base. tee hee.
=> imperial light mech doesn't require T2 mechatronics anymore

Resources/Prototypes/Entities/Markers/Spawners/Random/salvage.yml
Whups... Forgot to do that.
I actively tested it by loading up a copy of the game, and did some salvaging for half an hour. It spawns and it didn't explode the game.
=> Adds left out salvage to salvage spawning pools

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Fixed an issue where the circuit imprinter would not accept basic electronic parts despite many recipes requiring them
:cl: Pockets
- fix: Fix Circuit Imprinters not accepting Basic Electronic Parts
=> Fix Circuit Imprinters not accepting Basic Electronic Parts

Content.Shared/Cargo/Components/SharedCargoTelepadComponent.cs
reverts dogshit ee change that makes cargo pad take 10 seconds, makes them 2 seconds instead
=> cargopad-change

Resources/Prototypes/_Crescent/Entities/Objects/Ammunition/heavy_rifle.yml, Resources/Prototypes/_Crescent/Entities/Objects/Weapons/donator.yml, Resources/Prototypes/tags.yml
added a 12.7x99 speed loader because you cant load revolvers out of boxes
also moved the 12.7x99 box recipe to the proper yml oops
=> original donor gun speedloader because shitcode

Resources/Prototypes/Nyanotrasen/Entities/Body/Prototypes/felinid.yml, Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/Oni.yml, Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml, Resources/Prototypes/_Crescent/Entities/Body/Parts/felinid.yml
makes onis move faster the lower their HP is instead of slowing them down
makes felinids move faster than average
slightly adjust the mass of both species aswell
removes unneeded aphyx damage modifier from onis aswell which was there for some reason even though no melee in the game deals asphyx damage
=> port oni rage "mechanic" and felinids being faster from legacy

Resources/Prototypes/_Crescent/Entities/Factory/factory.yml, Resources/Prototypes/_Crescent/Entities/Recipes/Factory/munitions.yml
Adds 230mm high-explosive heavy mortar shells to the shell fabricator for 5 Tungsten-Carbidge.
Input can be changed to whatever on request, I wanted to cover a blind spot in munitions production since 230mms ROCK.
=> Add 230mm HE shells to the shell fabricator

Resources/Prototypes/_Crescent/Maps/Stations/jackal.yml
idk why they have more. the jackal + gsc roster + starting equipment were all designed around 12 guys.
=> gsc 12 slots

Resources/Prototypes/_Crescent/Maps/base.yml
Fix the cargo consoles of both traders not showing anything.
---
<p>
</p>
</details>
---
:cl:
- fix: PTA Gu Tian and SHI Kitamura cargo consoles are able to sell their goods again.
=> Pang Tai and SHI trader fix

Resources/Prototypes/_Crescent/Entities/Objects/Specific/fighters.yml
Modified variables through testing, gunship is slightly slower accel than fighters. 
INITIAL TUNE, all factions have same speeds.
Findings: Any friction actually does the complete opposite of what you want and makes them able to turn on a dime. 0 friction with low accel seems best!
=> WeightierfightersMK2. Faster, slower turn. More straight line.

Content.Shared/Clothing/MagbootsComponent.cs, Resources/Prototypes/Entities/Clothing/Shoes/magboots.yml, Resources/Prototypes/_Crescent/Entities/Clothing/Empire/Feet/boots.yml, Resources/Prototypes/_Crescent/Entities/Clothing/NCWL/Feet/boots.yml, Resources/Prototypes/_NF/Entities/Clothing/Shoes/magboots.yml
lowers the penalties of being active to 10% for civ/heavy variants and 5% for combat magboots.
no idea how the to fix bloodreds not showing their enabled icon
RELEASE ME.
=> Fix magboots for real this time

Resources/Prototypes/CharacterItemGroups/Generic/beltGroup.yml, Resources/Prototypes/_Crescent/Catalog/Fills/Belt/belt.yml, Resources/Prototypes/_Crescent/Entities/Clothing/SRM/belts.yml, Resources/Prototypes/_Crescent/Loadouts/Empire/belt.yml, Resources/Prototypes/_Crescent/Roles/Jobs/DSM/levyman.yml
Allows IPC to be Man at Arms in the DSM, would make sense for the imperial remnants to use the clankas in my opinion. Dueling khopesh available in loadouts for man at arms and higher ranks, is a worse machete but a quite larpy weapon, also man at arms don't get a cool side melee like higher ranks (with reason) but i feel like this one is fine.
---
---
<p>
</p>
</details>
---
:cl:
- add: Added Dueling Khopesh in loadouts for man at arms and higher ranks
- tweak: IPCs can be Man at Arms
=> IPCS as Man at Arms and loadout available dueling khopeshes for Man at Arms + 

Resources/Prototypes/_Crescent/Maps/Ships/Civilian/exhumermk2.yml
fixes a line from being Exhumerkmk2 (wrong way to spell) to Exhumermk2 (right way)
:cl:
- fix: Exhumer MKII prototype fix
=> Exhumer MKII prototype fix (i fixed spelling error)

Resources/Prototypes/_Crescent/Catalog/Cargo/PangTai/infantry.yml, Resources/Prototypes/_Crescent/Catalog/Fills/Crates/infantry.yml, Resources/Prototypes/_Crescent/Entities/Objects/Weapons/donator.yml
makes "XCR-6 charge rifle" available to be bought in the Pang Tai trader, it makes sense lore wise and the donator asked to be available to the common folk, (he owes me 200k in game too). The rifle is available at 35k and comes with diverse ammunition
---
<p>
</p>
</details>
---
:cl:
- tweak: XCR-6 charge rifle description
- adds: XCR-6 charge rifle to the Pang Tai trading console
=> PTA charger rifle available to be bought at the pang tai trader

Content.Server/_Crescent/ProjectilePhasePreventSystem.cs
this should fix the metadata issue in projectilephaseprevent - it was trying to raise an event (further down). so we check if the entity is deleted and then continue (onto the next, hopefully not deleted entity)
=> clears the metadata exception

Resources/Prototypes/_Crescent/Entities/Objects/Devices/pda.yml, Resources/Prototypes/_Crescent/Roles/Jobs/APRT/athpanzersanitat.yml, Resources/Prototypes/_Crescent/Roles/Jobs/ATH/sanitat.yml, Resources/Prototypes/_Crescent/Roles/Jobs/DSM/surgeon.yml, Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_doctor.yml, Resources/Prototypes/_Crescent/Roles/Jobs/SHI/medtech.yml, Resources/Prototypes/_Crescent/Roles/Jobs/SRM/tender.yml, Resources/Prototypes/_Crescent/Roles/Jobs/TFSC/ripperdoc.yml, Resources/Prototypes/_Crescent/Roles/Jobs/TFSC/traumasec.yml, Resources/Prototypes/_Crescent/Roles/Jobs/TSP/combatphysician.yml
Several medical roles were missing a medical analyzer in their PDA, a buff to surgery speed, CPR training or all three This PR standardizes all medical roles to have a medical analyzer and sets the surgery speed modifier for all medical roles to 1.75 (the standard for medical doctors on most codebases) with the exception of the ATH Chirurgeon which is 2.5 (same as CMO)
Players can still take the "experienced surgeon" trait to increase their surgery speed modifier to 2.5
:cl: Pockets
- tweak: Set surgery speed modifier to 1.75 for all medical roles except ATH Chirurgeon, which stays at 2.5
- tweak: Add medical analyzer to PDAs for all medical roles which did not already have it
- tweak: Add CPR training to medical roles that did not already have it
=> Standardize medical roles

Resources/Prototypes/_Crescent/Maps/Ships/SHI/bison.yml, Resources/Prototypes/_Crescent/Maps/Ships/SHI/buffalo.yml, Resources/Prototypes/_Crescent/Maps/Ships/SHI/gazpachov.yml, Resources/Prototypes/_Crescent/Maps/Ships/SHI/musinyane.yml, Resources/Prototypes/_Crescent/Maps/Ships/SHI/nazaar.yml, Resources/Prototypes/_Crescent/Maps/Ships/SHI/probe.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_shipyard.yml
Makes SHI ships overall cheaper (with the exception of nazaar which was priced at 25000 despite appraising for 27000/Flea being unchanged because its main price comes from its utility. Being incentivized to be sold to players directly for a higher price). 
Probe: 52k > 20k (Absolute dogshit to whoever priced it)
Musinyane:100k> 75k
Buffalo: 60k> 40k
Bison: 75k > 61k
Gazpachov: 70k > 52k
Also removes Gazpachov from the civillian shipyard. The best mining ship ingame should be available only through its manufacturer. Not to mention SHI itself doesn't have a civillian shipyard so it naturally needs to be as cheap as possible.
---
:cl:
- tweak: Lowered prices closer to the baselines (But not under the appraisegrid sell price).
- fix: Fixed nazaar selling for more than you bought it for.
- …
=> SHI Shipyard Changes

Resources/Prototypes/_Crescent/Entities/Clothing/FourFamilies/OuterClothing/armor.yml
FUCK YOU GITHUB.
FUCK. YOU. 
Draugr armor buff to allow them to actually utilize their melee and rely on their armor more. Having reskins of armors isn't good game design and their armor is currently just shitty DSM armor which folds like fucking paper in combat. Not great when you rely on a close-range melee weapon to kill people.
Buffs pierce resist to 50 (from 45)
Buffs armor health by 250 (1000 from 750)
Buffs heat resist to 25 (from 20)
Nerfs blunt resist by 5 (from 25
Nerfs caustic resist by 20 (from 25)
Buffs speed by 5% (10% from 15% speed decrease)
Kill them with hammers or throw acid on them
=> draugr armor rework WITH A BRANCH

Resources/Prototypes/_Crescent/Roles/Jobs/DSM/advocatus.yml, Resources/Prototypes/_Crescent/Roles/Jobs/DSM/governor.yml, Resources/Prototypes/_Crescent/Roles/Jobs/FourFamilies/antiquarian.yml, Resources/Prototypes/_Crescent/Roles/Jobs/FourFamilies/prophet.yml, Resources/Prototypes/_Crescent/Roles/Jobs/NCWL/ncwl_commandant.yml
added due to whitelists being broken and the antiquarian requiring mechanical knowledge to play correctly
TAP prophet also gets timelocked due to being FL
=> timelocks both antiquarian and lord admiral
